In [3]:
import pandas as pd
import re
from pathlib import Path

def parse_duration(d):
    match = re.match(r'PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?', d)
    hours = int(match.group(1) or 0)
    minutes = int(match.group(2) or 0)
    seconds = int(match.group(3) or 0)
    return f"{hours:02}:{minutes:02}:{seconds:02}"

df=pd.read_json('../datastore/videos.json')
display(df)
df['publishedAt']=pd.to_datetime(df['publishedAt']).dt.tz_localize(None)
df['duration'] = df['duration'].apply(parse_duration)
display(df.head(50))

if not Path('../datastore/videos_list.xlsx').exists():
    df.to_excel('../datastore/videos_list.xlsx',index_label='id')

,videoId,title,publishedAt,duration,viewCount,likeCount,commentCount
0,s79YFLmZRlY,Learn Data & AI Skills for FREE! Spring Skillu...,2026-04-27T16:15:51Z,PT20S,1349,14,0
1,K9Y8P3X45kE,SQL JOINs | INNER vs LEFT vs RIGHT vs FULL OUT...,2026-04-22T14:00:35Z,PT9M19S,2419,149,4
2,QLIdF4nPUk4,Learn SQL: Primary Keys #sql,2026-04-21T14:00:40Z,PT1M39S,5949,232,4
3,7ZWp03QAU_Q,Master new skills & level up your data + AI kn...,2026-04-20T14:00:11Z,PT39S,2397,50,0
4,qQ51wuIgM7E,Excel vs Power BI vs SQL vs Python | Restauran...,2026-04-15T14:01:32Z,PT21M4S,118808,3177,196
...,...,...,...,...,...,...,...
673,p6S9Gr1e4DQ,Learn Microsoft Excel Charts & Graphs,2021-01-26T15:00:17Z,PT1M19S,1261,13,0
674,c9KyB0IrRCc,Learn Microsoft Excel Formulas & Functions,2021-01-23T15:21:55Z,PT1M20S,5888,54,4
675,8_-RNgldpZI,Data Visualization with Tables vs Charts,2020-10-07T17:25:54Z,PT1M31S,1160,17,0
676,ztqDCnAjrWo,Why Learn Business Intelligence?,2020-10-07T17:16:17Z,PT3M56S,397,19,0
677,ZicVaFh8yoY,Maven Analytics: Become a DATA ROCKSTAR,2020-09-14T14:27:32Z,PT2M1S,3946,66,2

,videoId,title,publishedAt,duration,viewCount,likeCount,commentCount
0,s79YFLmZRlY,Learn Data & AI Skills for FREE! Spring Skillu...,2026-04-27 16:15:51,00:00:20,1349,14,0
1,K9Y8P3X45kE,SQL JOINs | INNER vs LEFT vs RIGHT vs FULL OUT...,2026-04-22 14:00:35,00:09:19,2419,149,4
2,QLIdF4nPUk4,Learn SQL: Primary Keys #sql,2026-04-21 14:00:40,00:01:39,5949,232,4
3,7ZWp03QAU_Q,Master new skills & level up your data + AI kn...,2026-04-20 14:00:11,00:00:39,2397,50,0
4,qQ51wuIgM7E,Excel vs Power BI vs SQL vs Python | Restauran...,2026-04-15 14:01:32,00:21:04,118808,3177,196
5,w0cjwIR9O7E,Learn Tableau: Sheet Swapping with Text #tableau,2026-04-14 14:01:29,00:02:39,5908,49,1
6,YaMvfOueBq8,Learn Python: Dummy Variables #python,2026-04-13 14:00:50,00:01:12,4485,111,1
7,4HW7KeLtPmc,Stop Using AI as a Search Engine: Build Custom...,2026-04-08 14:00:07,00:11:02,2007,61,1
8,r80gLbQSTG0,Learn Excel: Data Label For The Max Value #excel,2026-04-07 14:04:07,00:01:23,8890,220,1
9,PyQqiyIO60I,Learn Tableau: Extract Hack #tableau,2026-04-06 14:00:39,00:02:03,2242,26,0
10,D7rEhg13Ac0,Learn SQL: How to Filter Your Data Using the W...,2026-04-01 14:01:21,00:12:16,1407,78,1
11,Ob_iiDOaGy4,Learn Excel: Aggregate Time Data w/ Text #excel,2026-03-31 14:01:09,00:02:08,2615,107,4
12,Si5jn3Ca13c,Why your presentations are failing... #Shorts,2026-03-30 14:00:26,00:00:36,1934,35,1
13,_4SkiHcooEg,Why Your Presentations Fail (Even When Your Da...,2026-03-25 14:00:53,00:05:01,2870,162,8
14,cZ7lGdPYnys,Stop writing your own prompts. 🛑 #shorts,2026-03-24 14:01:01,00:00:52,2038,42,2
15,cGVnkw3qW2U,Can AI catch our mistake? 🤨 #datascience,2026-03-23 14:00:56,00:00:44,1750,20,1
16,henJv1DH2Ys,Text Classification with AI: The Easiest Way t...,2026-03-18 14:01:20,00:06:56,4666,191,8
17,Vd2V0fshbOU,Learn Python: Binning Data Using The Cut Funct...,2026-03-17 14:15:07,00:02:54,5831,113,0
18,dM6E7EA3K-g,Excel Showdown | Power Query vs Formulas vs Co...,2026-03-12 14:01:04,00:16:44,75051,2075,91
19,F-DGqVuZGW4,Learn Data: Context is King #data,2026-03-09 14:00:32,00:01:52,3722,180,3
20,0JZisMktcbA,How to Write the Perfect AI Prompt: Meta-Promp...,2026-03-04 15:00:02,00:11:49,3744,83,3
21,cB9-P7MFAXI,Learn Excel: Very Hidden Tabs #excel,2026-03-03 15:01:07,00:01:38,8003,200,1
22,p7zfbS8q928,Get LIFETIME Access to Maven Analytic +$1000 A...,2026-03-02 17:01:14,00:00:32,2208,27,0
23,eRWOdpludPM,"Getting Started with SQL | SELECT, FROM, WHERE...",2026-02-25 15:01:13,00:12:57,3731,193,2
24,kwJ9lMUXOSQ,$1000 OFF Maven Analytics + Analyst Builder LI...,2026-02-24 15:01:27,00:00:23,1735,11,1
25,p_vQGFVujB0,"How to Ace Your Data Job Interview (w/ ""Alex t...",2026-02-23 15:01:21,00:51:23,4248,157,5
26,kmTBohyePNE,Storytelling for Business Presentations (NEW ...,2026-02-19 13:01:21,00:01:57,1409,59,2
27,0G2z3QDMBZA,What hiring managers ACTUALLY look for in an i...,2026-02-17 15:00:03,00:00:41,3750,87,2
28,AiSis_eUHHc,Learn Python: Transpose #python,2026-02-16 15:00:31,00:01:00,7097,191,0
29,DqRVY9L9Ows,How Will AI Impact Data Careers?,2026-02-11 15:00:33,01:00:09,2807,83,9
30,SJh8EUkOUZU,Pro Tip: Look at your data regularly! #data,2026-02-10 15:00:49,00:00:47,1262,16,0
31,uZ--1PSofR8,Learn Power BI: Sort Month Names #powerbi,2026-02-09 15:01:43,00:01:57,4453,116,0
32,6_YO6yOG2_8,Learn Python: Create Simple & Clear Data Visua...,2026-02-04 15:00:11,00:09:43,2276,77,3
33,oHOUoCVJ5ik,"When presenting data, speak your audience’s la...",2026-02-03 15:01:25,00:00:33,1976,21,0
34,PVF5aPjCNLc,This or That with Data Analytics Experts #data,2026-02-02 15:00:49,00:00:46,16960,358,15
35,PDgtKkuHxu0,Master AI Prompt Writing in 1 Hour | The BRIDG...,2026-01-28 15:00:45,00:57:46,2129,80,4
36,YKUskD8CUxk,"""Data Storytelling is often the missing link i...",2026-01-27 15:01:05,00:01:37,2130,54,1
37,dbCgIdniZSU,Learn Python: Tornado Charts #python,2026-01-26 15:01:09,00:02:23,3187,94,0
38,FjxtntY5sO0,How to Join Tables in SQL | Clearly Explained ...,2026-01-21 15:00:34,00:07:46,7457,358,9
39,omTTLdHvgHA,Learn Excel: Unpivot Data! #excel,2026-01-20 15:01:36,00:02:17,4799,151,2
40,DY27yuiQRAY,Learn Python: Time Series Forecasting #python,2026-01-19 15:00:20,00:02:56,6964,316,3
41,E8Ts4ilL46Q,How to Use AI to Prep for Your Next Data Job I...,2026-01-14 15:00:25,00:13:34,1681,50,1
42,sjQY6DmHuM0,Learn Excel: Create Charts Inside Cells #excel,2026-01-13 15:01:43,00:02:02,5796,239,5
43,8Rn4dqgpNwY,Excel Pivot Tables: How to Create Raw Data in ...,2026-01-12 15:00:15,00:02:09,4114,146,0
44,Z2dPNiz6giI,How to Transform Your LinkedIn Profile with AI...,2026-01-07 15:01:07,00:10:55,5679,140,10
45,--OrmVkJbXc,Learn Python: Method Chaining #python,2026-01-06 15:00:00,00:01:01,9326,248,2
46,80nb95SAagw,January Jumpstart is LIVE! Learn Data & AI Ski...,2026-01-05 15:00:12,00:00:41,3472,71,0
47,P0VNg64f1hY,How to Use AI to Build Your Data Project Portf...,2026-01-01 15:00:44,00:18:21,4360,193,6
48,wTKT18kmWzI,9 Essential Chart Types for Data Analysts | Da...,2025-12-31 15:02:19,00:07:14,7615,299,3
49,3Rj1h8UzdQs,Learn SQL: The IN( ) Operator #sql,2025-12-30 15:00:06,00:00:59,22900,730,7