In [1]:
import pandas as pd
import re
from pathlib import Path

def parse_duration(d):
    match = re.match(r'PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?', d)
    hours = int(match.group(1) or 0)
    minutes = int(match.group(2) or 0)
    seconds = int(match.group(3) or 0)
    return f"{hours:02}:{minutes:02}:{seconds:02}"

df=pd.read_json('../datastore/videos.json')
display(df)
df['publishedAt']=pd.to_datetime(df['publishedAt']).dt.tz_localize(None)
df['duration'] = df['duration'].apply(parse_duration)
display(df)

if not Path('../datastore/videos_list.xlsx').exists():
    df.to_excel('../datastore/videos_list.xlsx',index_label='id')

,videoId,title,publishedAt,duration,viewCount,likeCount,commentCount
0,rv8IbmuArP0,The “New” Copilot in Excel | Live Demo (Datase...,2026-04-29T14:01:32Z,PT58M36S,947,43,3
1,PFTj3pmMI58,Learn Excel: Scenario Manager #excel,2026-04-28T14:00:43Z,PT3M,5261,223,2
2,s79YFLmZRlY,Learn Data & AI Skills for FREE! Spring Skillu...,2026-04-27T16:15:51Z,PT20S,1643,18,0
3,K9Y8P3X45kE,SQL JOINs | INNER vs LEFT vs RIGHT vs FULL OUT...,2026-04-22T14:00:35Z,PT9M19S,3235,178,4
4,QLIdF4nPUk4,Learn SQL: Primary Keys #sql,2026-04-21T14:00:40Z,PT1M39S,6047,237,4
...,...,...,...,...,...,...,...
675,p6S9Gr1e4DQ,Learn Microsoft Excel Charts & Graphs,2021-01-26T15:00:17Z,PT1M19S,1263,13,0
676,c9KyB0IrRCc,Learn Microsoft Excel Formulas & Functions,2021-01-23T15:21:55Z,PT1M20S,5903,54,4
677,8_-RNgldpZI,Data Visualization with Tables vs Charts,2020-10-07T17:25:54Z,PT1M31S,1161,17,0
678,ztqDCnAjrWo,Why Learn Business Intelligence?,2020-10-07T17:16:17Z,PT3M56S,397,19,0
679,ZicVaFh8yoY,Maven Analytics: Become a DATA ROCKSTAR,2020-09-14T14:27:32Z,PT2M1S,3947,66,2

,videoId,title,publishedAt,duration,viewCount,likeCount,commentCount
0,rv8IbmuArP0,The “New” Copilot in Excel | Live Demo (Datase...,2026-04-29 14:01:32,00:58:36,947,43,3
1,PFTj3pmMI58,Learn Excel: Scenario Manager #excel,2026-04-28 14:00:43,00:03:00,5261,223,2
2,s79YFLmZRlY,Learn Data & AI Skills for FREE! Spring Skillu...,2026-04-27 16:15:51,00:00:20,1643,18,0
3,K9Y8P3X45kE,SQL JOINs | INNER vs LEFT vs RIGHT vs FULL OUT...,2026-04-22 14:00:35,00:09:19,3235,178,4
4,QLIdF4nPUk4,Learn SQL: Primary Keys #sql,2026-04-21 14:00:40,00:01:39,6047,237,4
...,...,...,...,...,...,...,...
675,p6S9Gr1e4DQ,Learn Microsoft Excel Charts & Graphs,2021-01-26 15:00:17,00:01:19,1263,13,0
676,c9KyB0IrRCc,Learn Microsoft Excel Formulas & Functions,2021-01-23 15:21:55,00:01:20,5903,54,4
677,8_-RNgldpZI,Data Visualization with Tables vs Charts,2020-10-07 17:25:54,00:01:31,1161,17,0
678,ztqDCnAjrWo,Why Learn Business Intelligence?,2020-10-07 17:16:17,00:03:56,397,19,0
679,ZicVaFh8yoY,Maven Analytics: Become a DATA ROCKSTAR,2020-09-14 14:27:32,00:02:01,3947,66,2